sonar.projectKey=fabienmillet_ZLink_6337d0e1-b6b1-4ae7-9a8e-9e59e9dafa53

sonar.sources=core,widgets,windows,scripts,main.py
sonar.tests=tests
# Rapport produit par : pytest --cov --cov-report=xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**,build/**,dist/**,assets/**
